### ISSUE TITLE
bindException when run via "activator ui"

### ISSUE THREAD

**Issue by al11al** [adrianhurt/play-multidomain-seed#5]
Hey Adrian!

First of all thanks a lot for nice seed project!
I have an issue when running all projects on Ubuntu 14.04 
When I try to run via "activator run" everything works fine but when I try to run via "activator ui" it asks to addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.3.9") and then compiles well. But when project starts to run and netty tries to deploy, then only 1st named or 1st compiled project deploys successfully and works fine but console gives following error concerning 2nd project deployment: 

background log: info: 
background log: info: --- (Running the application, auto-reloading is enabled) ---
background log: info: 
background log: error: Play fork run has failed due to:
background log: error: java.lang.reflect.InvocationTargetException
background log: error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
background log: error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
background log: error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
background log: error: 	at java.lang.reflect.Method.invoke(Method.java:497)
background log: error: 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:197)
background log: error: 	at play.forkrun.ForkRun$.startServer(ForkRun.scala:82)
background log: error: 	at play.forkrun.ForkRun.run(ForkRun.scala:173)
background log: error: 	at play.forkrun.ForkRun$$anonfun$settingUp$1.applyOrElse(ForkRun.scala:162)
background log: error: 	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
background log: error: 	at play.forkrun.ForkRun.aroundReceive(ForkRun.scala:148)
background log: error: 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
background log: error: 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
background log: error: 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
background log: error: 	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
background log: error: 	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
background log: error: 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
background log: error: Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
background log: error: 	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
background log: error: 	at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:138)
background log: error: 	at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:135)
background log: error: 	at scala.Option.map(Option.scala:145)
background log: error: 	at play.core.server.NettyServer.<init>(NettyServer.scala:135)
background log: error: 	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:320)
background log: error: 	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:318)
background log: error: 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
background log: error: 	at play.core.server.NettyServer$.mainDev(NettyServer.scala:317)
background log: error: 	at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:313)
background log: error: 	at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
background log: error: 	... 19 more
background log: error: Caused by: java.net.BindException: Address already in use
background log: error: 	at sun.nio.ch.Net.bind0(Native Method)
background log: error: 	at sun.nio.ch.Net.bind(Net.java:437)
background log: error: 	at sun.nio.ch.Net.bind(Net.java:429)
background log: error: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
background log: error: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
background log: error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
background log: error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
background log: error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
background log: error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
background log: error: 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
background log: error: 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
background log: error: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
background log: error: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
background log: error: 	at java.lang.Thread.run(Thread.java:745)

Adrian , could you suggest, please, nice IDE to work with multi module projects.

**Comment by al11al** [comment]
Moved to correct repository https://github.com/adrianhurt/play-multidomain-auth/issues/4
