### ISSUE TITLE
Any plan to update to 2.5.x

### ISSUE THREAD

**Issue by dhirenpratap** [adrianhurt/play-multidomain-seed#7]
I tried doing myself but getting following exception
```
2016-05-10 13:02:29,956 - [ERROR] - p.c.s.n.PlayRequestHandler - Exception caught in Netty
scala.MatchError: Right((play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3@50a3f51b,play.api.DefaultApplication@2072c28f)) (of class scala.util.Right)
        at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:93)
        at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
        at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
2016-05-10 13:02:34,020 - [ERROR] - p.c.s.n.PlayRequestHandler - Exception caught in Netty
```

**Comment by adrianhurt** [comment]
Yes, I should update this repo as soon as possible. But now I don't have enough time to do it. Sorry

**Comment by adrianhurt** [comment]
I'm so sorry for the loooong delay, @dhirenpratap. I've had too busy months since then. I've just updated the seed to Play 2.5.
